version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: eParking_db
      MYSQL_USER: eparking_user
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - eparking_network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:

networks:
  eparking_network:
    driver: bridge
